### ISSUE TITLE
Add 'test site' to the 'Test category' category

### ISSUE THREAD

**Issue by kenman345** [kenman345/acceptbitcoincash#10]
Requesting to add 'test site' to the 'Test category' category. 

Details follow: 
```yml 
- name: test site
  url: https://acceptbitcoin.cash
  img: 
  twitter: usebitcoincash
  facebook: usebitcoincashFB
  email_address: 
  region: 
  country: US
  city: city
  bch: Yes
  btc: No
  othercrypto: No
  doc: httpsAnnouncement
  exceptions: 
    text: ""
```
