### ISSUE TITLE
Add 'Facebook' to the 'World domination' category

### ISSUE THREAD

**Issue by kenman345** [kenman345/acceptbitcoincash#11]
Requesting to add 'Facebook' to the 'World domination' category. 

Details follow: 
```yml 
- name: Facebook
  url: https://facebook.com
  img: https://en.facebookbrand.com/assets/f-logo
  twitter: Facebook
  facebook: Facebook
  email_address: facebook@facebook.com
  region: 
  country: 
  city: 
  bch: Yes
  btc: No
  othercrypto: No
  doc: 
  exceptions: 
    text: ""
```
