### ISSUE TITLE
Add 'Board of Governors of the Federal Reserve System' to the 'Banks' category

### ISSUE THREAD

**Issue by kenman345** [kenman345/acceptbitcoincash#12]
Requesting to add 'Board of Governors of the Federal Reserve System' to the 'Banks' category. 

Details follow: 
```yml 
- name: Board of Governors of the Federal Reserve System
  url: https://www.federalreserve.gov/
  img: https://www.federalreserve.gov/favicon.ico
  twitter: https://twitter.com/federalreserve
  facebook: N/A
  email_address: N/A
  region: 
  country: 
  city: Washington DC
  bch: Yes
  btc: No
  othercrypto: Yes
  doc: https://news.bitcoin.com/bitcoins-quirky-genesis-block-turns-eight-years-old-today/
  exceptions: 
    text: ""
```
