### ISSUE TITLE
Add 'Master of The Universe' to the 'Mature' category

### ISSUE THREAD

**Issue by kenman345** [kenman345/acceptbitcoincash#13]
Requesting to add 'Master of The Universe' to the 'Mature' category. 

Details follow: 
```yml 
- name: Master of The Universe
  url: www.heman.com
  img: 
  twitter: 
  facebook: 
  email_address: 
  region: na
  country: 
  city: 
  bch: No
  btc: No
  othercrypto: No
  doc: 
  exceptions: 
    text: ""
```
