### ISSUE TITLE
Add 'test' to the 'test' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [kenman345/acceptbitcoincash#14]
Requesting to add 'test' to the 'test' category. 

Details follow: 
```yml 
- name: test
      url: test
      img: 
      bch: No
      btc: No
      othercrypto: No
```
