### ISSUE TITLE
Add Accept BCH to the 'Wallets' category

### ISSUE THREAD

**Issue by kenman345** [kenman345/acceptbitcoincash#5]
Requesting to Add Accept BCH to the 'Wallets' category. 

Details follow: 

```yml 
- name: Accept BCH
  url: https://acceptbitcoin.cash
  img: https://acceptbitcoin.cash
  twitter: useBitcoinCash
  facebook: UseBitcoinCash
  region: 
  country: https://acceptbitcoin.cash
  city: https://acceptbitcoin.cash
  bch: No
  btc: No
  othercrypto: No
  doc: https://acceptbitcoin.cash
```

e.values[0] = 1/12/2018 15:20:58
e.values[1] = Accept BCH
e.values[2] = https://acceptbitcoin.cash
e.values[3] = https://imagur.com/123
e.values[4] = useBitcoinCash
e.values[5] = UseBitcoinCash
e.values[6] = No
e.values[7] = No
e.values[8] = No
e.values[9] = Wallets
e.values[10] = dfdfdfdf
e.values[11] = Global
e.values[12] =
