### ISSUE TITLE
Add 'Accept BCH' to the 'Web' category

### ISSUE THREAD

**Issue by kenman345** [kenman345/acceptbitcoincash#6]
Requesting to Add 'Accept BCH' to the 'Web' category. 

Details follow: 

```yml 
- name: Accept BCH
  url: https://acceptBitcoin.Cash
  img: sdsdaIMAGE
  twitter: useBitcoinCash
  facebook: FBUseBitcoinCash
  email_address: test@acceptBitcoin.cash
  region: 
  country: 
  city: 
  bch: Yes
  btc: No
  othercrypto: Yes
  doc: no URL
```

e.values[0] = 1/12/2018 21:39:35
e.values[1] = Accept BCH
e.values[2] = https://acceptBitcoin.Cash
e.values[3] = sdsdaIMAGE
e.values[4] = useBitcoinCash
e.values[5] = FBUseBitcoinCash
e.values[6] = Yes
e.values[7] = No
e.values[8] = Yes
e.values[9] = Web
e.values[10] = Just use tippr
e.values[11] = Global
e.values[12] = 
e.values[13] = 
e.values[14] = 
e.values[15] = no URL
e.values[16] = test@acceptBitcoin.cash
e.values[17] =
