### ISSUE TITLE
Add 'acceptBCH' to the 'WEB' category

### ISSUE THREAD

**Issue by kenman345** [kenman345/acceptbitcoincash#7]
Requesting to Add 'acceptBCH' to the 'WEB' category. 

Details follow: 

```yml 
- name: acceptBCH
  url: https://acceptbitcoin.cash
  img: iumage URL
  twitter: useBitcoinCash
  facebook: FB
  email_address: test@test.com
  region: 
  country: 
  city: 
  bch: Yes
  btc: No
  othercrypto: Yes
  doc: no url
  exceptions: 
    text: ""
```

e.values[0] = 1/12/2018 21:42:02
e.values[1] = acceptBCH
e.values[2] = https://acceptbitcoin.cash
e.values[3] = iumage URL
e.values[4] = useBitcoinCash
e.values[5] = FB
e.values[6] = Yes
e.values[7] = No
e.values[8] = Yes
e.values[9] = WEB
e.values[10] = Instructions to using BCH
e.values[11] = Global
e.values[12] = 
e.values[13] = 
e.values[14] = 
e.values[15] = no url
e.values[16] = test@test.com
e.values[17] =
