### ISSUE TITLE
Add 'makeme' to the 'cunt hoes' category

### ISSUE THREAD

**Issue by kenman345** [kenman345/acceptbitcoincash#8]
Requesting to Add 'makeme' to the 'cunt hoes' category. 

Details follow: 

```yml 
- name: makeme
  url: cunthoes.com
  img: cunthoes.com
  twitter: @cunthoes
  facebook: fb.com/cunthoes
  email_address: cunt@hoes.com
  region: af
  country: toronto
  city: canada
  bch: Yes
  btc: No
  othercrypto: No
  doc: cunthoes.com
  exceptions: 
    text: ""
```
