### ISSUE TITLE
Add 'Crypto Mercado' to the 'Food' category

### ISSUE THREAD

**Issue by kenman345** [kenman345/acceptbitcoincash#9]
Requesting to add 'Crypto Mercado' to the 'Food' category. 

Details follow: 
```yml 
- name: Crypto Mercado
  url: https://www.cryptomercado.com/
  img: https://scontent.ftpa1-2.fna.fbcdn.net/v/t1.0-9/12316648_200876800251116_1183965849246666295_n.png?oh=26fb38f54bdfc1c02a659722cc3abc81&oe=5AEC779E
  twitter: cryptomercado1
  facebook: cryptomercadodotcom
  email_address: 
  region: na
  country: 
  city: US
  bch: Yes
  btc: Yes
  othercrypto: Yes
  doc: none, I bought on their store with BCH myself several times
  exceptions: 
    text: ""
```
